version: "3.9"

services:
  application:
    build: ./application
    environment:
      - DOCKER_REDIS_URL=redis://redis:6379
    ports:
      - "5010:5010"
    volumes:
      - ./application/inputs:/app/inputs
    depends_on:
        - redis

  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379